### ISSUE TITLE
Suggestion: add `addy.io/login` redirection

### ISSUE THREAD

**Issue by o0nd7ots** [anonaddy/addy.io#30]
Hello,

sometimes when using anonaddy I try to log in by writing [addy.io/login](https://addy.io/login) into the browser search bar.
However, there is no login page on the main website.

To enter it one needs to go to the subdomain [app.addy.io](https://app.addy.io/), which prompts for a login.

I know that this is a neatpick so I can easily imagine ignoring this issue, but in the spirit of open source I bring this issue up.

**Comment by willbrowningme** [comment]
Thanks for the suggestion. I don't think I will add this, partly because many bots and spammers automatically try "addy.io/login" and I prefer that they simply receive a 404.
